//! A local, client-side store that pins a peer's full public key to their
//! nickname across sessions - the piece that's otherwise missing from this
//! app's identity model.
//!
//! `docs/PROTOCOL.md` §5.4/§11.2 already establish that a nickname is
//! trust-on-first-use and freed the instant its holder disconnects
//! (`UserId` never repeats, but nicknames do), and that a peer's announced
//! public key is otherwise accepted with no memory of what that nickname's
//! key was last time. That means nothing in the wire protocol distinguishes
//! "the same person reconnecting" from "someone else who took a familiar
//! nickname" - whether by coincidence or on purpose. This module closes
//! that gap locally, the same way SSH's `known_hosts` does: remember the
//! full key we saw for a nickname last time, and flag it loudly (never
//! silently block - this app has no "type yes to accept" flow, and a false
//! positive must never be able to lock out a legitimate reconnect) when it
//! comes back under a different one.
//!
//! The *full* DER-encoded key is stored, not just a hash of it: a SHA-256
//! fingerprint (still what `session::check_identity` shows in the
//! on-screen warning, via
//! `crypto::fingerprint_der`) is exactly as reliable for *detecting* a
//! change, but keeping only a hash throws away the one thing that would let
//! a user actually verify a pinned identity against a key file handed to
//! them out-of-band, or inspect what was pinned after the fact. These are
//! small keys (a few hundred bytes of DER) - there's no real storage cost
//! to keeping the real thing.
//!
//! **Byte comparison** (`check_and_pin` returning `Mismatch`, the check
//! `session::check_identity` drives) is only meaningful for the `KeyMode`s
//! whose key is actually the *same* key across two separate connections: a
//! `Rsa` `my_key` is loaded from a file (stable for as long as that file
//! is), and a `Password` `my_key` is deterministically re-derived from the
//! same password every time (`crypto::KeyPair::from_password` - same input,
//! same output). Both `KeyMode::None` and `KeyMode::PerMessage` are excluded
//! from *that* check: their key - including `PerMessage`'s *bootstrap* key,
//! not just the ones `rotate_for_peer` produces afterward - is freshly
//! autogenerated by `resolve_my_keypair` on every single connect, with
//! nothing persisted anywhere between sessions. Comparing either would flag
//! a false "possible impersonation" for the very same legitimate user on
//! every single reconnect - strictly worse than not checking at all, since
//! it trains a user to dismiss the warning instead of taking it seriously
//! when it actually matters.
//!
//! `PerMessage` peers do still get entries in this store, just written and
//! read by a different mechanism (`docs/PROTOCOL.md` §12.6): whenever
//! `session::handle_key_rotated` accepts a rotation it refreshes that
//! nickname's pin, and on the next reconnect `get` hands the pinned key back
//! as the fallback *verification anchor* for `rekey::verify_with_fallback`.
//! For those peers the pinned bytes are expected to change constantly and
//! `check_and_pin`'s return value is deliberately ignored - a signature that
//! verifies against neither anchor is the alarm condition there, never a byte
//! difference. `KeyMode::None` has no equivalent and stays entirely
//! untracked.

use std::collections::HashMap;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

/// Resolves the store path to prefill the connect popup with:
/// `~/.aloo/ids_store` (`crate::platform::aloo_dir()` joined with
/// `ids_store`), always - the program never reads or writes a loose file
/// in the current working directory of its own accord. Cross-platform:
/// see `crate::platform` for how `~` resolves on Linux, macOS and Windows.
/// This is only ever a suggestion - the path actually used for a session
/// is whatever ends up in `ConnectRequest::id_store_path` when the user
/// presses Connect, which starts out as this but is freely editable, so a
/// user who deliberately wants a different location (or a local one) can
/// still type it in.
pub fn default_path() -> PathBuf {
    crate::platform::aloo_dir().join("ids_store")
}

/// The result of checking one peer's announced identity against the store.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum IdCheck {
    /// This nickname has never been pinned before; it has been now.
    New,
    /// This nickname was already pinned to exactly this public key.
    Match,
    /// This nickname was pinned to a *different* public key last time - the
    /// signal this whole module exists to raise. The nickname is re-pinned
    /// to the new key regardless (there's no "reject and keep the old one"
    /// flow here - see the module doc), so a caller must act on this the
    /// moment it's returned; the previous key isn't recoverable from the
    /// store afterward, only from whatever the caller does with it here.
    Mismatch { previous_public_key_der: Vec<u8> },
}

/// A nickname -> full-public-key pinning store, backed by a small flat file
/// (`nickname<TAB><hex-encoded DER>` per line).
pub struct IdStore {
    path: PathBuf,
    entries: HashMap<String, Vec<u8>>,
}

impl IdStore {
    /// Starts an empty, in-memory-only store bound to `path` - used as a
    /// fallback when `load` fails for a reason other than the file simply
    /// not existing yet (e.g. a permissions error), so a caller can still
    /// run the session with pinning checks disabled for it rather than
    /// refusing to connect at all.
    pub fn new_empty(path: PathBuf) -> Self {
        Self {
            path,
            entries: HashMap::new(),
        }
    }

    /// Loads `path` if it exists; a missing file isn't an error (first run
    /// against this store) and just starts empty. Lines that don't parse as
    /// `name<TAB>hex` (or whose hex half doesn't decode) are skipped rather
    /// than failing the whole load, so a hand-edited or partially-corrupted
    /// file doesn't block connecting.
    pub fn load(path: &Path) -> io::Result<Self> {
        let mut entries = HashMap::new();
        match fs::read_to_string(path) {
            Ok(contents) => {
                for line in contents.lines() {
                    if let Some((name, hex)) = line.split_once('\t')
                        && is_storable(name)
                        && let Some(der) = hex_decode(hex)
                    {
                        entries.insert(name.to_string(), der);
                    }
                }
            }
            Err(e) if e.kind() == io::ErrorKind::NotFound => {}
            Err(e) => return Err(e),
        }
        Ok(Self {
            path: path.to_path_buf(),
            entries,
        })
    }

    /// Checks `nickname`'s announced `public_key_der` against what's pinned
    /// for it, pinning (or re-pinning) it in memory as a side effect -
    /// callers still need to call `save` to persist that. A nickname
    /// containing a tab or newline is never pinned or looked up (always
    /// returns `New` without touching `entries`): those bytes are
    /// attacker-controlled (an announced `display_name`), and the on-disk
    /// format uses exactly those characters as delimiters, so accepting one
    /// here would let a remote peer inject extra records into this local
    /// file. `public_key_der` itself has no such restriction - it's stored
    /// hex-encoded (see `save`), which can't contain either delimiter no
    /// matter what bytes it holds.
    pub fn check_and_pin(&mut self, nickname: &str, public_key_der: &[u8]) -> IdCheck {
        if !is_storable(nickname) {
            return IdCheck::New;
        }
        match self
            .entries
            .insert(nickname.to_string(), public_key_der.to_vec())
        {
            None => IdCheck::New,
            Some(previous) if previous == public_key_der => IdCheck::Match,
            Some(previous) => IdCheck::Mismatch {
                previous_public_key_der: previous,
            },
        }
    }

    /// Reads whatever is currently pinned for `nickname`, without pinning
    /// or mutating anything - used by the `rsa_per_msg` continuity/resume
    /// path (`docs/PROTOCOL.md` §12.6) to fetch a candidate verification
    /// anchor *before* deciding whether an incoming rotation is legitimate,
    /// which `check_and_pin` alone can't do (it always writes).
    pub fn get(&self, nickname: &str) -> Option<&[u8]> {
        self.entries.get(nickname).map(|v| v.as_slice())
    }

    /// Persists the current entries to `path`, creating parent directories
    /// if needed (e.g. `~/.aloo/` on first run). Entries are written in
    /// sorted order so the file diffs cleanly if the user inspects it, each
    /// key hex-encoded (rather than raw/base64) to match the plain-text,
    /// no-extra-dependency style already used elsewhere in this app
    /// (`crypto::fingerprint`'s own hex encoding).
    pub fn save(&self) -> io::Result<()> {
        if let Some(parent) = self.path.parent()
            && !parent.as_os_str().is_empty()
        {
            fs::create_dir_all(parent)?;
        }
        let mut names: Vec<&String> = self.entries.keys().collect();
        names.sort();
        let mut out = String::new();
        for name in names {
            out.push_str(name);
            out.push('\t');
            out.push_str(&hex_encode(&self.entries[name]));
            out.push('\n');
        }
        fs::write(&self.path, out)
    }
}

/// Whether `s` is safe to use as the nickname half of a
/// `name<TAB>hex-DER` line: no tab (the field delimiter) and no newline
/// (the record delimiter). The hex half never needs this check - hex digits
/// can't collide with either delimiter.
fn is_storable(s: &str) -> bool {
    !s.contains('\t') && !s.contains('\n') && !s.contains('\r')
}

fn hex_encode(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{:02x}", b));
    }
    s
}

/// Decodes a lowercase-hex string back to bytes; `None` on any malformed
/// input (odd length, non-hex character) rather than panicking, so a
/// corrupted line in a hand-edited store is simply dropped (`load`) instead
/// of taking down the whole store.
fn hex_decode(s: &str) -> Option<Vec<u8>> {
    if !s.len().is_multiple_of(2) {
        return None;
    }
    let mut out = Vec::with_capacity(s.len() / 2);
    let bytes = s.as_bytes();
    for chunk in bytes.chunks(2) {
        let hi = (chunk[0] as char).to_digit(16)?;
        let lo = (chunk[1] as char).to_digit(16)?;
        out.push((hi as u8) << 4 | lo as u8);
    }
    Some(out)
}
