//! Client-side connection bootstrap: drives the connect popup, then the
//! auth + identify handshake, before handing off to `crate::client::session`'s
//! ongoing connected-session loop.

use std::fs;
use std::io;
use std::io::Stdout;
use std::path::{Path, PathBuf};

use ratatui::Terminal;
use ratatui::backend::CrosstermBackend;
use tokio::net::TcpStream;

use crate::BoxError;
use crate::crypto;
use crate::client::idstore;
use crate::client::own_next_keys;
use crate::proto::{self, AuthKind, AuthResponse, ClientMessage, KeyMode, ServerMessage};
use crate::client::session;
use crate::client::tui::ui_connect_popup::{self, ConnectPopupState};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ServerKeySelection {
    None,
    Password(String),
    Rsa(PathBuf),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MyKeySelection {
    None,
    Password(String),
    Rsa {
        file_pub: PathBuf,
        file_priv: PathBuf,
    },
    /// `rsa_per_msg` (SPEC.md Functionality #6, PROTOCOL.md §11): the
    /// bootstrap keypair itself is always freshly autogenerated in-process
    /// at connect time, same as `None` - but `own_next_keys_path` still
    /// needs collecting, since it's where this client's own per-peer
    /// continuity private keys are persisted across reconnects
    /// (`docs/PROTOCOL.md` §12.6), letting a peer verify "it's still me"
    /// after this client comes back online.
    RsaPerMessage {
        own_next_keys_path: PathBuf,
    },
    /// `pq_hybrid` (`docs/PROTOCOL.md` §13): both files are keybundles
    /// produced by `aloo --keygen-pq-hybrid`, not PEM - same two-file
    /// shape as `Rsa`, different file format underneath.
    PqHybrid {
        file_pub: PathBuf,
        file_priv: PathBuf,
    },
}

/// What the user asked to connect with, as collected by the connect popup
/// (`tui::ui_connect_popup`) and consumed by the handshake here.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConnectRequest {
    pub host: String,
    pub port: u16,
    pub nickname: String,
    pub server_key: ServerKeySelection,
    pub my_key: MyKeySelection,
    /// Where the local identity-pinning store lives (see
    /// `aloo::idstore`, `docs/PROTOCOL.md` §12) - the file that remembers
    /// each nickname's full public key from the last time it was seen (for
    /// `rsa`/`password`), so a reconnecting peer whose key suddenly changed
    /// can be flagged instead of silently trusted. Prefilled from
    /// `idstore::default_path` but freely editable.
    pub id_store_path: PathBuf,
}

/// This client's own resolved key material, whichever `my_key` type
/// produced it. Replaces a bare `RsaPrivateKey` return once `PqHybrid`
/// needed to carry a whole `crypto::pq::PqPrivateBundle` instead - every
/// other `my_key` type still resolves to a plain RSA keypair exactly as
/// before. `pub` so `resolve_my_keypair`'s return type is externally
/// nameable (see its own doc comment).
pub enum ResolvedIdentity {
    Rsa(crypto::KeyPair),
    Pq {
        private: crypto::pq::PqPrivateBundle,
        /// Bincode-encoded `crypto::pq::PqPublicBundle`, precomputed here
        /// (once, from `file_pub`) since `Identify`'s `public_key_der` needs
        /// it and `PqPrivateBundle` alone can't derive it back out.
        public_der: Vec<u8>,
    },
}

/// A distinct error type so `run_client_inner` can tell "the server
/// rejected this nickname" apart from other, fatal handshake failures via
/// `downcast_ref` and loop back to the popup instead of exiting.
#[derive(Debug)]
struct NicknameTakenError(String);

impl std::fmt::Display for NicknameTakenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl std::error::Error for NicknameTakenError {}

pub async fn run_client_inner(
    terminal: &mut Terminal<CrosstermBackend<Stdout>>,
    port: u16,
    keyboard_release_reporting: bool,
    hotkey_rx: Option<tokio::sync::mpsc::UnboundedReceiver<crate::client::global_ptt::GlobalPttEvent>>,
) -> Result<(), BoxError> {
    let mut popup = ConnectPopupState::new();
    popup.port = port.to_string();
    popup.nickname = local_display_name();

    let mut cache = load_connect_cache();
    prefill_connect_defaults(&mut popup, &cache, &crate::platform::aloo_dir());

    loop {
        let Some(request) = ui_connect_popup::run(terminal, &mut popup)? else {
            return Ok(()); // user cancelled
        };

        // Remembered regardless of whether the connection attempt below
        // actually succeeds ("the last values used in the popup", not "the
        // last successful connection") - a wrong password or an
        // unreachable host doesn't mean the pq_hybrid identity chosen was
        // wrong.
        if let MyKeySelection::PqHybrid {
            file_pub,
            file_priv,
        } = &request.my_key
        {
            cache.record(
                &request.host,
                request.port,
                &file_pub.display().to_string(),
                &file_priv.display().to_string(),
            );
            if let Err(e) = cache.save() {
                eprintln!("aloo: failed to save connect cache: {e}");
            }
        }

        match connect_and_handshake(&request).await {
            Ok((rd, wr, you, identity, key_mode, server_addr)) => {
                let id_store = load_id_store(&request.id_store_path);
                let own_next_keys = match &request.my_key {
                    MyKeySelection::RsaPerMessage { own_next_keys_path } => {
                        Some(load_own_next_keys(own_next_keys_path))
                    }
                    _ => None,
                };
                return session::run_connected_session(
                    terminal,
                    rd,
                    wr,
                    request.nickname,
                    you,
                    identity,
                    key_mode,
                    keyboard_release_reporting,
                    id_store,
                    own_next_keys,
                    hotkey_rx,
                    server_addr,
                )
                .await;
            }
            Err(e) => {
                let Some(taken) = e.downcast_ref::<NicknameTakenError>() else {
                    return Err(e);
                };
                // Loop back to the popup instead of exiting: everything the
                // user already filled in (host, keys, ...) stays put, only
                // the nickname needs to change.
                popup.error = Some(taken.0.clone());
                popup.focus = ui_connect_popup::Field::Nickname;
            }
        }
    }
}

/// Connects, then runs the auth + identify handshake. On success returns
/// the split stream halves, the `UserId` the server assigned us, our
/// private key (needed to decrypt incoming messages), and the `KeyMode`
/// this session runs under (`PerMessage` for `rsa_per_msg` - see
/// `rekey`). A taken nickname comes back as `NicknameTakenError` so the
/// caller can retry instead of treating it as fatal.
async fn connect_and_handshake(
    request: &ConnectRequest,
) -> Result<
    (
        tokio::io::ReadHalf<TcpStream>,
        tokio::io::WriteHalf<TcpStream>,
        proto::UserId,
        ResolvedIdentity,
        KeyMode,
        std::net::SocketAddr,
    ),
    BoxError,
> {
    let (identity, key_mode) = resolve_my_keypair(&request.my_key)?;

    let stream = TcpStream::connect((request.host.as_str(), request.port)).await?;
    // The server's UDP rendezvous socket binds the same numeric port on the
    // same address (`server::run`) - captured here, before the stream
    // splits, since `peer_addr` needs the whole `TcpStream` and this is the
    // resolved address (DNS already settled), not just whatever hostname
    // the user typed.
    let server_addr = stream.peer_addr()?;
    let (mut rd, mut wr) = tokio::io::split(stream);

    let Some(ServerMessage::Hello { auth, challenge }) = proto::read_message(&mut rd).await? else {
        return Err("server closed the connection during handshake".into());
    };
    let response = build_auth_response(auth, challenge, &request.server_key)?;
    proto::write_message(&mut wr, &ClientMessage::Auth(response)).await?;

    let Some(ServerMessage::AuthResult { ok, reason }) = proto::read_message(&mut rd).await? else {
        return Err("server closed the connection during authentication".into());
    };
    if !ok {
        return Err(format!("authentication failed: {}", reason.unwrap_or_default()).into());
    }

    let public_key_der = match &identity {
        ResolvedIdentity::Rsa(kp) => crypto::public_key_to_der(&kp.public)?,
        ResolvedIdentity::Pq { public_der, .. } => public_der.clone(),
    };
    proto::write_message(
        &mut wr,
        &ClientMessage::Identify {
            display_name: request.nickname.clone(),
            public_key_der,
            key_mode,
        },
    )
    .await?;

    let Some(ServerMessage::IdentifyResult { ok, you, reason }) =
        proto::read_message(&mut rd).await?
    else {
        return Err("server closed the connection during identify".into());
    };
    if !ok {
        return Err(Box::new(NicknameTakenError(
            reason.unwrap_or_else(|| "nickname rejected".to_string()),
        )));
    }
    let you = you.ok_or("server accepted identify but returned no user id")?;

    Ok((rd, wr, you, identity, key_mode, server_addr))
}

/// `rsa_per_msg` (`MyKeySelection::RsaPerMessage`) always autogenerates a
/// fresh bootstrap keypair in-process, exactly like `None` - except at
/// `crypto::RSA_PER_MSG_KEY_BITS` (4096) rather than the usual
/// `RSA_KEY_BITS`, matching every key `rekey::OwnKeys` rotates to
/// afterward. `PqHybrid` is the odd one out: unlike every other type, it's
/// never generated in-process here - always loaded from the keybundle files
/// `aloo --keygen-pq-hybrid` produces (`docs/PROTOCOL.md` §13), the same
/// way `Rsa` loads PEM files. The `KeyMode` announced in `Identify` is what
/// switches on per-peer rotation (`PerMessage`) or the hybrid scheme
/// (`PqHybrid`) for the rest of the session.
/// `pub` (rather than the usual `connect.rs`-private helper) purely so
/// `test/connect_test.rs` can exercise the `PqHybrid` arm's auto-generate
/// behavior directly - it needs no live socket, unlike the rest of the
/// connect/handshake flow, so it doesn't need the socket-based end-to-end
/// coverage the rest of this file relies on (`docs/TESTING.md`'s
/// `connect.rs` exception).
pub fn resolve_my_keypair(sel: &MyKeySelection) -> Result<(ResolvedIdentity, KeyMode), BoxError> {
    match sel {
        MyKeySelection::None => Ok((
            ResolvedIdentity::Rsa(crypto::KeyPair::generate()?),
            KeyMode::None,
        )),
        MyKeySelection::Password(pw) => Ok((
            ResolvedIdentity::Rsa(crypto::KeyPair::from_password(pw)?),
            KeyMode::Password,
        )),
        MyKeySelection::Rsa {
            file_pub,
            file_priv,
        } => Ok((
            ResolvedIdentity::Rsa(crypto::KeyPair::load_from_files(file_priv, file_pub)?),
            KeyMode::Rsa,
        )),
        MyKeySelection::RsaPerMessage { .. } => Ok((
            ResolvedIdentity::Rsa(crypto::KeyPair::generate_with_bits(
                crypto::RSA_PER_MSG_KEY_BITS,
            )?),
            KeyMode::PerMessage,
        )),
        MyKeySelection::PqHybrid {
            file_pub,
            file_priv,
        } => {
            // Transparently generates a fresh keybundle at these exact
            // paths if either is missing - covers both a freshly-assigned,
            // not-yet-generated location (`fresh_pq_hybrid_paths_in`) and a
            // path the user typed by hand that simply doesn't exist yet.
            crypto::pq::ensure_bundle_at(file_pub, file_priv)?;
            let private = crypto::pq::load_private_bundle(file_priv)?;
            let public = crypto::pq::load_public_bundle(file_pub)?;
            let public_der = proto::encode(&public)?;
            Ok((
                ResolvedIdentity::Pq {
                    private,
                    public_der,
                },
                KeyMode::PqHybrid,
            ))
        }
    }
}

fn build_auth_response(
    auth_kind: AuthKind,
    challenge: Option<Vec<u8>>,
    server_key: &ServerKeySelection,
) -> Result<AuthResponse, BoxError> {
    match (auth_kind, server_key) {
        (AuthKind::None, _) => Ok(AuthResponse::None),
        (AuthKind::Password, ServerKeySelection::Password(pw)) => {
            Ok(AuthResponse::Password(pw.clone()))
        }
        (AuthKind::Rsa, ServerKeySelection::Rsa(path)) => {
            let server_pub = crypto::load_public_key(path)?;
            let nonce = challenge.ok_or("server requires rsa auth but sent no challenge")?;
            let blocks = crypto::encrypt_chunked(&server_pub, &nonce)?;
            Ok(AuthResponse::Rsa { blocks })
        }
        (kind, _) => Err(format!(
            "server requires {kind:?} auth but no matching server_key was provided"
        )
        .into()),
    }
}

fn local_display_name() -> String {
    std::env::var("USER")
        .or_else(|_| std::env::var("USERNAME"))
        .unwrap_or_else(|_| "anon".to_string())
}

/// Loads the local identity-pinning store from the connect popup's
/// `id_store` field (`docs/PROTOCOL.md` §12). A load failure for any
/// reason other than "file doesn't exist yet" (e.g. a permissions error)
/// doesn't block connecting - it falls back to an empty, in-memory-only
/// store for this session instead, since refusing to connect over a local
/// bookkeeping-file problem would be a worse outcome than simply running
/// this session without pinning checks.
fn load_id_store(path: &std::path::Path) -> idstore::IdStore {
    match idstore::IdStore::load(path) {
        Ok(store) => store,
        Err(e) => {
            eprintln!(
                "aloo: failed to load id_store at {}: {e} (continuing this session without identity pinning)",
                path.display()
            );
            idstore::IdStore::new_empty(path.to_path_buf())
        }
    }
}

/// Loads this client's own per-peer `rsa_per_msg` continuity keys
/// (`docs/PROTOCOL.md` §12.6) from the connect popup's `own_next_keys`
/// field - only called when `my_key` is `rsa_per_msg`. Same fallback
/// policy as `load_id_store`: a load failure other than "file doesn't
/// exist yet" starts an empty, in-memory-only store rather than blocking
/// the connection - this session just won't be able to resume-prove
/// continuity to any peer until a fresh rotation re-seeds it.
fn load_own_next_keys(path: &std::path::Path) -> own_next_keys::OwnNextKeys {
    match own_next_keys::OwnNextKeys::load(path) {
        Ok(store) => store,
        Err(e) => {
            eprintln!(
                "aloo: failed to load own_next_keys at {}: {e} (continuing this session without resume continuity)",
                path.display()
            );
            own_next_keys::OwnNextKeys::new_empty(path.to_path_buf())
        }
    }
}

// ---------------------------------------------------------------------
// Connect-popup field cache (`~/.aloo/.cache`, `docs/HOW.md`)
//
// Remembers, per (host, port), the `pq_hybrid` keybundle files last used
// to connect there - so relaunching the app (or reconnecting to the same
// server later in the same launch) prefills the popup instead of starting
// from a blank/freshly-random identity every time. Paired with
// `crypto::pq::ensure_bundle_at` (called from `resolve_my_keypair`'s
// `PqHybrid` arm), which transparently generates the actual key material
// the first time a given location is actually used to connect - between
// the two, `pq_hybrid` (this app's default `my_key` type) never requires
// the user to run `aloo --keygen-pq-hybrid` by hand.
// ---------------------------------------------------------------------

/// Resolves the connect-cache file's path: `~/.aloo/.cache`, same
/// cross-platform `~` resolution as `idstore`/`own_next_keys`
/// (`platform::aloo_dir`).
pub fn cache_path() -> PathBuf {
    crate::platform::aloo_dir().join(".cache")
}

/// One remembered connect-popup state for a specific `(host, port)`.
#[derive(Clone, PartialEq, Eq, Debug)]
struct CachedConnection {
    host: String,
    port: u16,
    pq_file_pub: String,
    pq_file_priv: String,
}

/// Small local store of "the last connect-popup values used, per (host,
/// port)". The *most recently used* entry (`most_recent`) prefills a
/// freshly-opened popup's host/port/`pq_hybrid` file fields - see
/// `prefill_connect_defaults` - so reconnecting to the same server, or
/// simply relaunching the app, doesn't need retyping anything, and each
/// server gets its own remembered `pq_hybrid` identity rather than one
/// global default.
///
/// Backed by a flat `host<TAB>port<TAB>file_pub<TAB>file_priv`-per-line
/// file, oldest-used first / most-recently-used last - the same
/// tab-delimited, forgiving-of-a-missing-file-or-a-malformed-line
/// conventions `idstore::IdStore` and `own_next_keys::OwnNextKeys` already
/// use, for the same reasons (a hand-edited or partially-corrupted cache
/// must never block connecting).
pub struct ConnectCache {
    path: PathBuf,
    entries: Vec<CachedConnection>,
}

impl ConnectCache {
    /// Starts an empty, in-memory-only cache bound to `path` - used as a
    /// fallback when `load` fails for a reason other than the file simply
    /// not existing yet, mirroring `idstore::IdStore::new_empty`.
    pub fn new_empty(path: PathBuf) -> Self {
        Self {
            path,
            entries: Vec::new(),
        }
    }

    /// Loads `path` if it exists; a missing file isn't an error (first run
    /// - "if .cache file does not exist, use the current defaults") and
    /// just starts empty. A line that doesn't parse as exactly
    /// `host<TAB>port<TAB>file_pub<TAB>file_priv`, or whose port isn't a
    /// valid `u16`, is skipped rather than failing the whole load.
    pub fn load(path: &Path) -> io::Result<Self> {
        let mut entries = Vec::new();
        match fs::read_to_string(path) {
            Ok(contents) => {
                for line in contents.lines() {
                    let parts: Vec<&str> = line.split('\t').collect();
                    if let [host, port, file_pub, file_priv] = parts[..]
                        && let Ok(port) = port.parse::<u16>()
                    {
                        entries.push(CachedConnection {
                            host: host.to_string(),
                            port,
                            pq_file_pub: file_pub.to_string(),
                            pq_file_priv: file_priv.to_string(),
                        });
                    }
                }
            }
            Err(e) if e.kind() == io::ErrorKind::NotFound => {}
            Err(e) => return Err(e),
        }
        Ok(Self {
            path: path.to_path_buf(),
            entries,
        })
    }

    /// The most recently used entry, if any: `(host, port, file_pub, file_priv)`.
    pub fn most_recent(&self) -> Option<(&str, u16, &str, &str)> {
        self.entries.last().map(|e| {
            (
                e.host.as_str(),
                e.port,
                e.pq_file_pub.as_str(),
                e.pq_file_priv.as_str(),
            )
        })
    }

    /// Records `(host, port) -> (file_pub, file_priv)` as the most recently
    /// used entry, replacing any existing entry for the same pair (rather
    /// than duplicating it) so it moves to the end. Callers still need to
    /// call `save` to persist this. A `host`/`file_pub`/`file_priv`
    /// containing a tab, newline or carriage return is silently skipped
    /// (never stored) - `host` is user-typed input sitting next to this
    /// file's own delimiters, same reasoning as `IdStore::check_and_pin`.
    pub fn record(&mut self, host: &str, port: u16, file_pub: &str, file_priv: &str) {
        if !is_storable(host) || !is_storable(file_pub) || !is_storable(file_priv) {
            return;
        }
        self.entries.retain(|e| !(e.host == host && e.port == port));
        self.entries.push(CachedConnection {
            host: host.to_string(),
            port,
            pq_file_pub: file_pub.to_string(),
            pq_file_priv: file_priv.to_string(),
        });
    }

    /// Persists all entries to `path`, creating parent directories if
    /// needed - same conventions as `idstore::IdStore::save`.
    pub fn save(&self) -> io::Result<()> {
        if let Some(parent) = self.path.parent()
            && !parent.as_os_str().is_empty()
        {
            fs::create_dir_all(parent)?;
        }
        let mut out = String::new();
        for e in &self.entries {
            out.push_str(&e.host);
            out.push('\t');
            out.push_str(&e.port.to_string());
            out.push('\t');
            out.push_str(&e.pq_file_pub);
            out.push('\t');
            out.push_str(&e.pq_file_priv);
            out.push('\n');
        }
        fs::write(&self.path, out)
    }
}

/// Whether `s` is safe to use as a field in this cache's tab-delimited
/// lines - no tab (field delimiter), no newline/carriage-return (record
/// delimiter). Mirrors `own_next_keys::is_storable`, duplicated rather than
/// shared - each of this app's small flat-file stores keeps its own copy,
/// consistent with `idstore.rs`/`own_next_keys.rs` already doing the same.
fn is_storable(s: &str) -> bool {
    !s.contains('\t') && !s.contains('\n') && !s.contains('\r')
}

/// Loads the connect cache from its default path (`~/.aloo/.cache`),
/// falling back to an empty in-memory-only cache on any load failure other
/// than "doesn't exist yet" - same fallback policy, and reasoning, as
/// `load_id_store`/`load_own_next_keys`: a broken local cache must never
/// block connecting.
fn load_connect_cache() -> ConnectCache {
    let path = cache_path();
    match ConnectCache::load(&path) {
        Ok(cache) => cache,
        Err(e) => {
            eprintln!(
                "aloo: failed to load connect cache at {}: {e} (continuing without it)",
                path.display()
            );
            ConnectCache::new_empty(path)
        }
    }
}

/// A 4-character lowercase-alphanumeric prefix for a freshly-assigned
/// `pq_hybrid` keybundle location - 36^4 (~1.68M) combinations, plenty for
/// a directory that will realistically hold at most a handful of these
/// files at once.
pub fn random_prefix() -> String {
    const ALPHABET: &[u8] = b"abcdefghijklmnopqrstuvwxyz0123456789";
    crypto::random_bytes(4)
        .iter()
        .map(|b| ALPHABET[*b as usize % ALPHABET.len()] as char)
        .collect()
}

/// Picks a `(file_pub, file_priv)` pair under `dir` that doesn't collide
/// with anything already there, trying up to 20 times (far more than the
/// birthday bound needs for `random_prefix`'s ~1.68M-value space against a
/// directory this small) before giving up and returning the last attempt
/// regardless. Does **not** create the files itself - `resolve_my_keypair`'s
/// `crypto::pq::ensure_bundle_at` call does that, the first time this
/// location is actually used to connect - so a location can be assigned
/// (and shown in the popup, and cached) well before any key material
/// actually exists on disk.
pub fn fresh_pq_hybrid_paths_in(dir: &Path) -> (PathBuf, PathBuf) {
    for _ in 0..20 {
        let prefix = random_prefix();
        let file_pub = dir.join(format!("{prefix}.pub"));
        let file_priv = dir.join(format!("{prefix}.priv"));
        if !file_pub.exists() && !file_priv.exists() {
            return (file_pub, file_priv);
        }
    }
    let prefix = random_prefix();
    (
        dir.join(format!("{prefix}.pub")),
        dir.join(format!("{prefix}.priv")),
    )
}

/// Prefills `popup`'s host/port/`pq_hybrid` file fields, once, before it's
/// ever shown - the same one-shot-at-open convention `id_store`/
/// `own_next_keys`/`nickname` already use (not reactively as the user
/// edits host/port afterward):
///
/// - If `cache` has a most-recently-used entry, restores its host, port,
///   and `pq_hybrid` keybundle paths - `my_key.key_type` is set to
///   `PqHybrid` explicitly since restoring file paths only makes sense
///   paired with that type.
/// - Otherwise (first run - no cache yet), leaves host/port alone and
///   assigns a fresh, not-yet-generated `pq_hybrid` location under `dir`
///   (`fresh_pq_hybrid_paths_in`), so the default `my_key` type is
///   immediately connectable without the user needing to prepare anything
///   first.
pub fn prefill_connect_defaults(popup: &mut ConnectPopupState, cache: &ConnectCache, dir: &Path) {
    if let Some((host, port, file_pub, file_priv)) = cache.most_recent() {
        popup.host = host.to_string();
        popup.port = port.to_string();
        popup.my_key.key_type = ui_connect_popup::MyKeyType::PqHybrid;
        popup.my_key.file_pub = file_pub.to_string();
        popup.my_key.file_priv = file_priv.to_string();
    } else {
        let (file_pub, file_priv) = fresh_pq_hybrid_paths_in(dir);
        popup.my_key.file_pub = file_pub.display().to_string();
        popup.my_key.file_priv = file_priv.display().to_string();
    }
}
